# Generated by Django 3.0.3 on 2020-02-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrId', models.IntegerField()),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('deployDate', models.DateField()),
            ],
        ),
    ]
