# Generated by Django 3.0.3 on 2020-03-01 00:25

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('campusId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.Campus')),
                ('trashPlaceId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.TrashPlace')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
