# Generated by Django 3.0.3 on 2020-02-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('server', '0002_trashuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrashUser',
        ),
    ]
