# Generated by Django 3.0.3 on 2020-03-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200301_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashstats',
            name='campusId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='trashstats',
            name='trashPlaceId',
            field=models.IntegerField(default=-1),
        ),
    ]
