# Generated by Django 3.0.3 on 2020-02-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_delete_trashuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrashPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('pictureCoordinateX', models.IntegerField()),
                ('pictureCoordinateY', models.IntegerField()),
                ('qrCodeData', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Empty trash can'), (1, 'Filled trash can'), (2, 'No trash can')])),
                ('campusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='TrashStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throwDate', models.DateField()),
                ('trashPlaceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.TrashPlace')),
            ],
        ),
        migrations.DeleteModel(
            name='TrashCan',
        ),
    ]
