# Generated by Django 3.0.3 on 2020-02-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200229_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashplace',
            name='qrCodeData',
        ),
    ]
