# Generated by Django 3.0.3 on 2020-02-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_trashplace_qrcodedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashplace',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
