# Generated by Django 3.0.3 on 2020-03-01 01:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('server', '0005_auto_20200301_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnPermission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Permission')),
                ('permission', models.IntegerField(default=0)),
                ('trashPlaceId', models.IntegerField(default=-1)),
                ('campusId', models.IntegerField(default=-1)),
            ],
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.DeleteModel(
            name='OwnUser',
        ),
    ]
