# Generated by Django 3.0.3 on 2020-03-01 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200301_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashstats',
            name='requestDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ownpermission',
            name='permission',
            field=models.IntegerField(choices=[(0, 'nothing'), (1, 'employee'), (2, 'operator')], default=0),
        ),
        migrations.AlterField(
            model_name='trashstats',
            name='cleanDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
