# Generated by Django 3.0.3 on 2020-02-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_trashplace_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashplace',
            name='campusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trashplaces', to='server.Campus'),
        ),
    ]
