# Generated by Django 3.0.3 on 2020-03-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200301_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashstats',
            name='requestDate',
            field=models.DateField(),
        ),
    ]
