# Generated by Django 3.0.3 on 2020-03-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_estimatedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimatedTime', models.DateTimeField()),
                ('campusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Campus')),
                ('themostpopularid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.TrashPlace')),
            ],
        ),
        migrations.DeleteModel(
            name='EstimatedTime',
        ),
    ]
