# Generated by Django 3.0.3 on 2020-03-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20200301_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusstats',
            old_name='themostpopularid',
            new_name='themostpopular',
        ),
    ]
